[project]
name = "memory-proxy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.3.5",
    "fastapi>=0.123.0",
    "httpx>=0.28.1",
    "ipadic>=1.0.0",
    "mecab-python3>=1.0.12",
    "openai>=2.8.1",
    "python-dotenv>=1.2.1",
    "ruff>=0.14.7",
    "sqlalchemy>=2.0.44",
    "uvicorn>=0.38.0",
]
